version: '3'

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: learnapp
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
